Import Upstream version 0.71

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1499,7 +1499,7 @@ fi
 
 PACKAGE=mtr
 
-VERSION=0.70
+VERSION=0.71
 
 if test "`cd $srcdir && pwd`" != "`pwd`" && test -f $srcdir/config.status; then
   { { echo "$as_me:$LINENO: error: source directory already configured; run \"make distclean\" there first" >&5
@@ -6882,6 +6882,78 @@ _ACEOF
   LIBS="-lresolv $LIBS"
 
 else
+
+echo "$as_me:$LINENO: checking for __res_mkquery in -lresolv" >&5
+echo $ECHO_N "checking for __res_mkquery in -lresolv... $ECHO_C" >&6
+if test "${ac_cv_lib_resolv___res_mkquery+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lresolv  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char __res_mkquery ();
+int
+main ()
+{
+__res_mkquery ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_resolv___res_mkquery=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_resolv___res_mkquery=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_resolv___res_mkquery" >&5
+echo "${ECHO_T}$ac_cv_lib_resolv___res_mkquery" >&6
+if test $ac_cv_lib_resolv___res_mkquery = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBRESOLV 1
+_ACEOF
+
+  LIBS="-lresolv $LIBS"
+
+else
   { { echo "$as_me:$LINENO: error: No resolver library found" >&5
 echo "$as_me: error: No resolver library found" >&2;}
    { (exit 1); exit 1; }; }
@@ -6891,6 +6963,9 @@ fi
 
 fi
 
+fi
+
+LIBS="$LIBS -lresolv"
 
 echo "$as_me:$LINENO: checking for herror" >&5
 echo $ECHO_N "checking for herror... $ECHO_C" >&6
